version: "3.0"

services:
  backend:
    volumes:
      - ./backend:/app
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    ports:
      - 8080:8080

  frontend:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - ./frontend:/src # ローカルをコンテナ内にマウント
    command: sh -c "cd react-project && yarn start" # コンテナを立ち上げた時に自動的にbuild
    ports:
      - 3000:3000

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
